name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Create a virtual environment first
          uv venv
          # Activate the virtual environment
          source .venv/bin/activate
          # Install pre-commit
          uv pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          # Activate the virtual environment
          source .venv/bin/activate
          # Run pre-commit hooks
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Try to use uv if available, otherwise fall back to pip
          if command -v uv &> /dev/null; then
            # Create a virtual environment first
            uv venv
            # Activate the virtual environment
            source .venv/bin/activate
            # Install dependencies
            uv pip install -e .
          else
            pip install -e .
          fi

      - name: Run tests
        run: |
          # If using uv, activate the virtual environment first
          if command -v uv &> /dev/null && [ -d ".venv" ]; then
            source .venv/bin/activate
          fi
          make test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Generate test report
        run: |
          # If using uv, activate the virtual environment first
          if command -v uv &> /dev/null && [ -d ".venv" ]; then
            source .venv/bin/activate
          fi
          mkdir -p tests/scripts/test_results
          bash tests/scripts/api_tests.sh

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: tests/scripts/test_results/test_report.md

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: |
          # Create a virtual environment first
          uv venv
          # Activate the virtual environment
          source .venv/bin/activate
          # Install build dependencies
          uv pip install build twine

      - name: Build package
        run: |
          # Activate the virtual environment
          source .venv/bin/activate
          # Build the package
          python -m build

      - name: Check package
        run: |
          # Activate the virtual environment
          source .venv/bin/activate
          # Check the package
          twine check dist/*

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
